### ISSUE TITLE
Bug: various glitches on "Reply" sample

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [material-components/material-components-android-examples#57]
I just noticed these:

![image](https://user-images.githubusercontent.com/5357526/92310305-bb607000-efb5-11ea-8da0-c7b872f8f81b.png)

![image](https://user-images.githubusercontent.com/5357526/92310317-d16e3080-efb5-11ea-85b0-57a404ebd4d6.png)

And yet in other places I don't see those. Example:

![image](https://user-images.githubusercontent.com/5357526/92310322-dcc15c00-efb5-11ea-862e-fe10a84c28f3.png)

**Comment by hunterstich** [comment]
Hey @AndroidDeveloperLB ,

Those earmarks are part of the design and are used to mark an email as "starred". If you swipe an email from left to right, you can mark/unmark an email, changing a list item's top-left corner shape.

**Comment by AndroidDeveloperLB** [comment]
@hunterstich Earmarks? It doesn't look well at all. It looks like a glitch. Seems outside of the card, as if someone forgot about the background behind...
It's supposed to be a CardView, no? Why would something be attached to it on the corner, and this way...
Are there actual real apps that use this style?
I didn't see it on Gmail, for example (though its UI doesn't have a list of cards). Even on the messy UI of Google NewsStand I don't see it.

Why is it this way? Can you please show me this on the guidelines? I never saw such a thing.

**Comment by hunterstich** [comment]
It's a way to [show state using shape](https://material.io/design/shape/shape-as-expression.html#communicating-state). Owl, the other sample in this repository, does something similar to show an item as checked/unchecked:

![owl_shape_checked_state](https://user-images.githubusercontent.com/7459254/92517513-c816db00-f1e4-11ea-9b40-d2cc2fdd8bfe.png)

**Comment by AndroidDeveloperLB** [comment]
@hunterstich Guys this doesn't look well at all and doesn't look intuitive, and seems against material design which has depth for cards. It looks like a bug...

Why would a card have a weird tiny background behind it?
Its content is supposed to be the one that shows it's checked. Not what's behind it...
The card's content is already what's being focused on. Having something outside of it doesn't make it clear enough that it's chosen this way. If at all, you should have put an outline around the card, and not on a single corner of it. Look at what Google Photos does when you select photos. It shrinks the photo a bit, puts a clear checkbox in the corner and that's it. 
If instead you would have changed its shape to have rounded corner and put a tiny background there, it would be very unclear to see that this is what it means.

Even on Gmail, where it doesn't have cards, it doesn't use this. Instead it has a star icon which is also easy to toggle (just press it), instead of swiping this way...

Why change the shape of the card or put some tiny background behind it, if it already has a checkbox ? It doesn't make sense...
